### ISSUE TITLE
Problems in "Overview Notebook" with "poster" style

### ISSUE THREAD

**Issue by boustrephon** [chrystalchern/mdof#1]
I tried running the Overview Notebook and I got an error relating to SciencePlots as below due to use of the "poster" style. Should I contact them or is this something this repository can address?

<img width="940" alt="image" src="https://github.com/chrystalchern/mdof/assets/14007454/78f1ae9d-fabf-4453-b8de-3485a5c587ad">

**Comment by boustrephon** [comment]
UPDATE: I changed "poster" to "notebook" in line 7 of `printing.py` and it ran fine. I am using VS Code to run the notebooks.

**Comment by chrystalchern** [comment]
Thanks for letting me know!  I've incorporated this.  Feel free to `pip install -U mdof` and pull to update and let me know if the problem persists.

**Comment by boustrephon** [comment]
Yes. That fixed it. 

Incidentally, where can I look for some of the explanation and theoretical background to these analyses, especially the meaning of the "stabilization" plot?

**Comment by boustrephon** [comment]
Fixed

**Comment by chrystalchern** [comment]
Great!  Theoretical background is provided here https://chrystalchern.github.io/mdof/theory/index.html but does not include explanation of stabilization diagram.
Stabilization diagram compares system identification results with model order.  Periods and damping ratios which are consistent across model orders are the most trustworthy. The lowest model order with the consistent periods and damping ratios is the most likely model order.
Example use of stabilization diagram in Figure 13 of this paper: https://doi.org/10.1016/j.engstruct.2017.08.066
